name: Nix
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v12
        with:
          name: numtide
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ./run-tests.sh
